apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-dispatcherhq
patches:
  - path: deployment-patch.yaml
resources:
  - ../../base
  - ingress.yaml
images:
  - name: kodenobi/dispatcherhq-client
    newTag: cf43711
